appServer:
  image:
    repository: tommydevv1/demo-api
    tag: latest
  service:
    type: ClusterIP

appWeb:
  image:
    repository: tommydevv1/cafe-web
    tag: latest
  service:
    type: ClusterIP

appIngress:
  status: disabled
