apiVersion: v1
kind: Service
metadata:
  name: app-server
  labels:
    io.kompose.service: app-server
spec:
  type: {{ .Values.appServer.service.type }}
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    io.kompose.service: app-server
