apiVersion: v1
kind: Service
metadata:
  name: app-server
  labels:
    io.kompose.service: app-server
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
      name: http
  selector:
    io.kompose.service: app-server
