apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-out.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app-server
  name: app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-out.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/app-server-network: "true"
        io.kompose.service: app-server
    spec:
      containers:
        - image: "{{ .Values.app-server.image.repository }}:{{ .Values.app-server.image.tag }}"
          name: app-server
          ports:
            - containerPort: 8090
          env:
            - name: spring.datasource.url
              value: "jdbc:mysql://app-db/api-demo-db-dev"
          resources: {}
      restartPolicy: Always
status: {}
